spring.application.name=acesso
spring.datasource.url={URL DO SEU BANCO}
spring.datasource.username={USER NAME DO SEU BANCO}
spring.datasource.password={SENHA DO SEU BANCO}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
